In [1]:
import time

import numpy as np

from fmm import Fmm
from fmm.kernel import *

In [2]:
e = Fmm('test')

In [3]:
e.run()

In [4]:
s = time.time()
r1 = laplace_gradient(e.sources, e.targets, e.source_densities)
print(f'Compile time {time.time()-s}')

Compile time 1.4166638851165771


In [9]:
s = time.time()
r2 = laplace_gradient(e.sources, e.targets, e.source_densities)
print(f'Run time {time.time()-s}')

Run time 1.4686241149902344


In [10]:
e = Fmm('test')

In [11]:
s = time.time()
e.run()
print(f'Run time {time.time()-s}')

Run time 0.37634825706481934


In [13]:
e.target_potentials

array([[ 555.02246,  282.95575,  602.39734,  448.9055 ],
       [ 507.7668 ,  728.1406 ,  836.08984,  150.34557],
       [ 567.05273,  733.8954 ,  423.6351 ,  367.00122],
       ...,
       [ 515.74805, -463.98212, -511.38147, -427.25092],
       [ 535.14954, -305.47162, -636.3563 , -557.47595],
       [ 549.2261 , -272.41443, -617.6881 ,  -90.58121]], dtype=float32)

In [6]:
r1

array([[ 283.3415 ,  602.8579 ,  448.8763 ],
       [ 728.319  ,  836.0533 ,  150.27887],
       [ 731.808  ,  421.88794,  366.041  ],
       ...,
       [-464.09085, -511.3172 , -427.3405 ],
       [-305.128  , -636.4044 , -557.71857],
       [-272.34122, -617.55475,  -90.45561]], dtype=float32)

In [5]:
r1

array([[ 283.34146,  602.8579 ,  448.87628],
       [ 728.319  ,  836.0532 ,  150.27887],
       [ 731.808  ,  421.88797,  366.04095],
       ...,
       [-464.09082, -511.3172 , -427.3405 ],
       [-305.12805, -636.4044 , -557.71857],
       [-272.3412 , -617.5548 ,  -90.45561]], dtype=float32)

In [4]:
r2

NameError: name 'r2' is not defined